### ISSUE TITLE
retrieve all genes from the Williams Trend Test from command line

### ISSUE THREAD

**Issue by d-pellegrino** [auerbachs/BMDExpress-2#22]
With BMD express 2.3 it is possible to get all genes after the Williams Trend Test by setting the p-value cutoff to “None” and unclicking the fold change box. After the test, it is possible to see that the the p-value cutoff reported when choosing None is 999999. However, from command line the pValueCutoff in the json file can only accept numeric values between 0 - 1, and setting it to 999999 does not provide to me the same results and raises the following error: 

```
import expression: /var/tmp/835c5931db75433dc54f3365f6cfd20e/BMD_input/
Starting Williams Trend Test
Finished Williams Trend Test
bmd analysis on group null
java.lang.NullPointerException
	at com.sciome.bmdexpress2.commandline.AnalyzeRunner.doBMDSAnalysis(AnalyzeRunner.java:445)
	at com.sciome.bmdexpress2.commandline.AnalyzeRunner.analyze(AnalyzeRunner.java:138)
	at com.sciome.bmdexpress2.commandline.BMDExpressCommandLine.run(BMDExpressCommandLine.java:123)
	at com.sciome.bmdexpress2.commandline.BMDExpressCommandLine.main(BMDExpressCommandLine.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
	at install4j.com.sciome.bmdexpress2.commandline.BMDExpressCommandLine.main(Unknown Source)
Error:null
usage: bmdexpress2-cmd --version
usage: bmdexpress2-cmd analyze --config-file <JSON>
    --config-file <JSON>
usage: bmdexpress2-cmd export --analysis-group <GROUP> [--analysis-name <NAME>] --input-bm2 <BM2FILE> --output-file-name <OUTPUT>
    --analysis-group <GROUP>
    --analysis-name <NAME>
    --input-bm2 <BM2FILE>
    --output-file-name <OUTPUT>
usage: bmdexpress2-cmd delete --analysis-group <GROUP> --analysis-name <NAME> --input-bm2 <BM2FILE>
    --analysis-group <GROUP>
    --analysis-name <NAME>
    --input-bm2 <BM2FILE>
usage: bmdexpress2-cmd query --analysis-group <GROUP> --input-bm2 <BM2FILE>
    --analysis-group <GROUP>
    --input-bm2 <BM2FILE>
usage: bmdexpress2-cmd combine --input-bm2-files <INPUT BM2 FILES> --output-file-name <OUTPUT>
    --input-bm2-files <INPUT BM2 FILES>
    --output-file-name <OUTPUT>
<GROUP>: expression, anova, williams, oriogen, bmd, categorical
```

How could this be solved in order to get the correct number of genes also when using the command line? I attached my json as txt so it could be uploaded here.
Thank you!
[bmdx_config.json.txt](https://github.com/auerbachs/BMDExpress-2/files/6642234/bmdx_config.json.txt)

**Comment by burgerga** [comment]
Might be an issue on my end, because the `bmdsConfig` json is missing required arguments. We will fix the json and see if the issue is still there...

**Comment by d-pellegrino** [comment]
Without the bmdsConfig part in the json file the williams trend test was executed and all the genes retrieved. Thanks for the indications and for solving this point!
